### ISSUE TITLE
Not all nodes are being assigned communities

### ISSUE THREAD

**Issue by aaalissa** [WGUNDERWOOD/motifcluster#4]
Hi there,

I've been working with the [SNAP email-Eu-core dataset](https://snap.stanford.edu/data/email-Eu-core.html) and attempting to apply motif clustering using a Python script. However, I'm encountering an issue with the number of nodes that are being assigned to motif clusters compared to the actual number of nodes in the graph.

Specifically, the number of nodes assigned to clusters seems to vary based on the selected motif name. 

For instance, when running this command, I only receive assignments for 972 of the 1005 nodes:
```
motif_cluster = mccl.run_motif_clustering(eu_core_csr_matrix, motif_name="M8", num_clusts=42, motif_type="func",
                                          mam_weight_type="mean", mam_method="sparse", type_lap="rw", num_eigs=4)

```

I'm trying to understand why there's such a variance in the number of node assignments and why not all nodes are being assigned to a cluster. Any insights into how the choice of motif, along with other parameters in the function, might be influencing these results would be greatly appreciated.

Thank you in advance for any assistance or suggestions!

**Comment by WGUNDERWOOD** [comment]
I expect this is probably due to the fact that the `motifcluster` methodology provides clusters only for nodes in the largest connected component of the network induced by the motif adjacency matrix with the selected motif, to avoid creating trivial partitions. See Section 3.3.2 in [our paper](https://arxiv.org/abs/2004.01293). In practical terms, if you want a cluster for each node, I would suggest one of the following:

1) After you run `motifcluster`, you can access the list of which nodes have successfully been allocated to a partition (i.e. the largest connected component of the motif adjacency matrix) with the `comps` attribute (see the [docs](https://motifcluster.readthedocs.io/en/latest/index.html)). Then you can remove these nodes from the network and run `motifcluster` again. Repeat until you have identified all the clusters.

2) You can try modifying the original network to ensure its motif adjacency matrix is connected. Exactly how you do this will depend on the motif used, and this might skew the intended results as you are editing the data.

**Comment by aaalissa** [comment]
Ah, I see. Thank you for the prompt response!
